import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import './styles.css';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:10000/api';
const api=axios.create({baseURL:API_BASE});
api.interceptors.request.use(c=>{const t=localStorage.getItem('career_token');if(t)c.headers.Authorization=`Bearer ${t}`;return c;});

function Auth({onLogin}){const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{const url=mode==='login'?'/auth/login':'/auth/register';const r=await api.post(url,form);localStorage.setItem('career_token',r.data.token);onLogin(r.data.user);}catch(e){setError(e.response?.data?.error||'Server error');}finally{setLoading(false)}};
 return <div className="auth"><div className="card auth-card"><h1>CareerStack</h1><p>Smart job search for your career.</p><form onSubmit={submit}>{mode==='register'&&<input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?'Please wait...':mode==='login'?'Login':'Create account'}</button></form><button className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'New user? Register':'Already have an account? Login'}</button></div></div>}

function App(){const [user,setUser]=useState(null),[tab,setTab]=useState('jobs'),[jobs,setJobs]=useState([]),[apps,setApps]=useState([]),[profile,setProfile]=useState(null),[questions,setQuestions]=useState([]),[q,setQ]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{try{const [u,j,a,i]=await Promise.all([api.get('/me'),api.get('/jobs'),api.get('/applications'),api.get('/interview')]);setUser(u.data);setProfile(u.data);setJobs(j.data);setApps(a.data);setQuestions(i.data)}catch(e){localStorage.removeItem('career_token');setUser(null)}};
 useEffect(()=>{if(localStorage.getItem('career_token'))load()},[]);
 if(!user)return <Auth onLogin={u=>{setUser(u);load()}}/>;
 const search=async()=>{const r=await api.get('/jobs',{params:{q}});setJobs(r.data)};
 const apply=async id=>{try{await api.post(`/jobs/${id}/apply`);setMessage('Application submitted');const r=await api.get('/applications');setApps(r.data)}catch(e){setMessage(e.response?.data?.error||'Could not apply')}};
 const saveProfile=async()=>{const r=await api.put('/profile',profile);setProfile(r.data);setUser(r.data);setMessage('Profile updated')};
 const logout=()=>{localStorage.removeItem('career_token');setUser(null)};
 return <div><header><div className="brand">CareerStack</div><nav>{[['jobs','Jobs'],['applications','Applications'],['profile','Profile'],['interview','Interview']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}<button onClick={logout}>Logout</button></nav></header><main><div className="welcome"><div><h2>Hi, {user.name}</h2><p>Find jobs that match your skills.</p></div>{message&&<div className="notice">{message}</div>}</div>{tab==='jobs'&&<><div className="search"><input placeholder="Search jobs, skills or companies" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()}/><button onClick={search}>Search</button></div><div className="grid">{jobs.map(j=><article className="card job" key={j.id}><div className="jobtop"><h3>{j.title}</h3><span>{j.match_percentage}% match</span></div><b>{j.company}</b><p>{j.location} · {j.experience}</p><p>{j.description}</p><small>Skills: {j.skills}</small><button onClick={()=>apply(j.id)}>Apply</button></article>)}</div></>}{tab==='applications'&&<div className="card"><h2>My Applications</h2>{apps.length?apps.map(a=><div className="row" key={a.id}><div><b>{a.title}</b><p>{a.company} · {a.location}</p></div><span>{a.status}</span></div>):<p>No applications yet.</p>}</div>}{tab==='profile'&&profile&&<div className="card form"><h2>Profile</h2><input value={profile.name||''} placeholder="Name" onChange={e=>setProfile({...profile,name:e.target.value})}/><select value={profile.experience_level||'fresher'} onChange={e=>setProfile({...profile,experience_level:e.target.value})}><option value="fresher">Fresher</option><option value="experienced">Experienced</option></select><input value={profile.location||''} placeholder="Preferred location" onChange={e=>setProfile({...profile,location:e.target.value})}/><textarea value={profile.skills||''} placeholder="Skills, comma separated" onChange={e=>setProfile({...profile,skills:e.target.value})}/><button onClick={saveProfile}>Save Profile</button></div>}{tab==='interview'&&<div className="grid">{questions.map((x,i)=><article className="card" key={i}><h3>{x.question}</h3><p>{x.tip}</p></article>)}</div>}</main></div>}

createRoot(document.getElementById('root')).render(<App/>);
